param(
    [ValidateSet("setup", "status", "logs", "stop", "help")]
    [string]$Action = "setup"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Set-Location $PSScriptRoot

$EnvFile = if ($env:ENV_FILE) { $env:ENV_FILE } else { ".env.quickstart" }
$ComposeFiles = @("-f", "docker-compose.yml", "-f", "docker-compose.local.yml")

function Show-Usage {
    Write-Host @"
Usage: .\quick-docker-setup.ps1 [setup|status|logs|stop]

  setup   Create a local environment, build images, and start FinSight (default)
  status  Show container status
  logs    Follow logs from all local services
  stop    Stop containers without deleting local data

Optional: set ENV_FILE to use another environment file.
"@
}

function Invoke-Compose {
    param([string[]]$ComposeArgs)

    & docker compose --env-file $EnvFile @ComposeFiles @ComposeArgs
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Compose command failed with exit code $LASTEXITCODE."
    }
}

function Assert-Docker {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker is not installed. Install and start Docker Desktop first."
    }

    & docker compose version *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "The Docker Compose plugin is not available."
    }

    & docker info *> $null
    if ($LASTEXITCODE -ne 0) {
        throw "Docker Desktop is not running or is not accessible."
    }
}

function New-RandomSecret {
    $bytes = New-Object byte[] 24
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    }
    finally {
        $generator.Dispose()
    }

    return -join ($bytes | ForEach-Object { $_.ToString("x2") })
}

function New-LocalEnvironment {
    if (Test-Path -LiteralPath $EnvFile) {
        Write-Host "Using existing $EnvFile"
        return
    }

    $mysqlRootPassword = New-RandomSecret
    $dbPassword = New-RandomSecret
    $redisPassword = New-RandomSecret

    $content = @"
# Generated by quick-docker-setup.ps1 for local development only.
TZ=Asia/Ho_Chi_Minh
JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Ho_Chi_Minh

MYSQL_ROOT_PASSWORD=$mysqlRootPassword
DB_HOST=mysql
DB_PORT=3306
DB_JDBC_URL=jdbc:mysql://mysql:3306/finsight?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
DB_USER=finsight
DB_PASSWORD=$dbPassword
DB_NAME=finsight

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=$redisPassword
REDIS_DATABASE=0
REDIS_CACHE_TTL=3600

KAFKA_URLS=kafka:19092
KAFKA_TOPIC_MARKET_DATA=market-data
KAFKA_TOPIC_WEBHOOKS=market-payment
KAFKA_TOPIC_REST=market-rest
KAFKA_TOPIC_INGESTION=market-ingestion
KAFKA_TOPIC_INGESTION_REPLY=
KAFKA_REQUEST_TIMEOUT_MS=15000

MQTT_URL=tcp://mosquitto:1883
MQTT_USERNAME=
MQTT_PASSWORD=
MQTT_TOPIC_MARKET_DATA=market-data

# The optional live-market profile needs real authorized DNSE values.
DATAFEED_TOKENURL=wss://datafeed-lts-krx.dnse.com.vn:443/wss
DATAFEED_INVERSTORURL=unused-unless-live-market-profile-is-enabled
DATAFEED_WEBSOCKETURL=unused-unless-live-market-profile-is-enabled
DATAFEED_USERNAME=
DATAFEED_PASSWORD=

# Placeholders keep the core demo bootable. Payments require real PayOS credentials.
PAYOS_CLIENT_ID=unused-unless-payments-are-enabled
PAYOS_API_KEY=unused-unless-payments-are-enabled
PAYOS_CHECKSUM_KEY=unused-unless-payments-are-enabled

MAIL_HOST=smtp.example.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=

VITE_API_BASE_URL=http://localhost:8080
VITE_INGESTION_API_BASE_URL=http://localhost:8080/ingestion
VITE_MQTT_BROKER_URL=ws://localhost:9001/mqtt
VITE_MQTT_TOPIC=market-data
APP_DOMAIN=localhost:8080
"@

    $utf8WithoutBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($EnvFile, $content, $utf8WithoutBom)
    Write-Host "Created $EnvFile with generated local passwords."
}

function Wait-ForKafka {
    Write-Host "Waiting for Kafka..."
    for ($attempt = 1; $attempt -le 60; $attempt++) {
        & docker compose --env-file $EnvFile @ComposeFiles exec -T kafka `
            /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server kafka:19092 *> $null
        if ($LASTEXITCODE -eq 0) {
            return
        }
        Start-Sleep -Seconds 2
    }

    throw "Kafka did not become ready. Run .\quick-docker-setup.cmd logs for details."
}

function New-KafkaTopics {
    $topics = @("market-data", "market-payment", "market-rest", "market-ingestion")
    foreach ($topic in $topics) {
        Invoke-Compose -ComposeArgs @(
            "exec", "-T", "kafka",
            "/opt/kafka/bin/kafka-topics.sh",
            "--create", "--if-not-exists",
            "--topic", $topic,
            "--partitions", "3",
            "--replication-factor", "1",
            "--bootstrap-server", "kafka:19092"
        )
    }
    Write-Host "Kafka topics are ready."
}

function Wait-ForGateway {
    Write-Host "Waiting for the REST health check..."
    for ($attempt = 1; $attempt -le 90; $attempt++) {
        & docker compose --env-file $EnvFile @ComposeFiles exec -T gateway `
            wget -qO- http://localhost/health *> $null
        if ($LASTEXITCODE -eq 0) {
            Write-Host "FinSight is ready."
            return
        }
        Start-Sleep -Seconds 2
    }

    throw "The health check did not pass. Run .\quick-docker-setup.cmd logs for details."
}

function Start-FinSightStack {
    New-LocalEnvironment
    Invoke-Compose -ComposeArgs @("config", "--quiet")

    Write-Host "Starting MySQL, Redis, Kafka, and MQTT..."
    Invoke-Compose -ComposeArgs @(
        "up", "-d", "--wait", "--wait-timeout", "180",
        "mysql", "redis", "kafka", "mosquitto"
    )
    Wait-ForKafka
    New-KafkaTopics

    Write-Host "Building FinSight images. The first build can take several minutes..."
    Invoke-Compose -ComposeArgs @(
        "build", "--pull",
        "market-rest-1", "market-rest-2", "market-ingestion",
        "market-realtime", "market-frontend"
    )

    Write-Host "Starting the core FinSight application..."
    Invoke-Compose -ComposeArgs @(
        "up", "-d",
        "market-realtime", "market-rest-1", "market-rest-2",
        "market-ingestion", "market-frontend", "gateway"
    )

    Wait-ForGateway
    Invoke-Compose -ComposeArgs @("ps")
    Write-Host ""
    Write-Host "FinSight: http://localhost:8080"
    Write-Host "Health:   http://localhost:8080/health"
    Write-Host "Swagger:  http://localhost:8080/api-docs/"
    Write-Host ""
    Write-Host "A new MySQL volume is initialized from the bundled thesis database snapshot."
    Write-Host "Payment and live-market integrations are disabled until configured."
}

try {
    switch ($Action) {
        "setup" {
            Assert-Docker
            Start-FinSightStack
        }
        "status" {
            Assert-Docker
            if (-not (Test-Path -LiteralPath $EnvFile)) {
                throw "Missing $EnvFile. Run .\quick-docker-setup.cmd first."
            }
            Invoke-Compose -ComposeArgs @("ps")
        }
        "logs" {
            Assert-Docker
            if (-not (Test-Path -LiteralPath $EnvFile)) {
                throw "Missing $EnvFile. Run .\quick-docker-setup.cmd first."
            }
            Invoke-Compose -ComposeArgs @("logs", "--tail=200", "-f")
        }
        "stop" {
            Assert-Docker
            if (-not (Test-Path -LiteralPath $EnvFile)) {
                throw "Missing $EnvFile. Run .\quick-docker-setup.cmd first."
            }
            Invoke-Compose -ComposeArgs @("down")
        }
        "help" {
            Show-Usage
        }
    }
}
catch {
    Write-Error $_.Exception.Message
    exit 1
}
