#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

ENV_FILE="${ENV_FILE:-.env.quickstart}"
COMPOSE_FILES=(-f docker-compose.yml -f docker-compose.local.yml)
ACTION="${1:-setup}"

usage() {
  cat <<'EOF'
Usage: ./quick-docker-setup.sh [setup|status|logs|stop]

  setup   Create a local environment, build images, and start FinSight (default)
  status  Show container status
  logs    Follow logs from all local services
  stop    Stop containers without deleting local data

Optional: set ENV_FILE=/path/to/file to use another environment file.
EOF
}

fail() {
  echo "Error: $*" >&2
  exit 1
}

compose() {
  docker compose --env-file "$ENV_FILE" "${COMPOSE_FILES[@]}" "$@"
}

require_docker() {
  command -v docker >/dev/null 2>&1 || fail "Docker is not installed. See DOCKER_SETUP_GUIDE.md section 5."
  docker compose version >/dev/null 2>&1 || fail "The Docker Compose plugin is not installed."
  docker info >/dev/null 2>&1 || fail "The Docker daemon is not running or is not accessible by this user."
}

random_secret() {
  od -An -N24 -tx1 /dev/urandom | tr -d ' \n'
}

create_local_env() {
  if [[ -f "$ENV_FILE" ]]; then
    echo "Using existing $ENV_FILE"
    return
  fi

  local mysql_root_password db_password redis_password
  mysql_root_password="$(random_secret)"
  db_password="$(random_secret)"
  redis_password="$(random_secret)"

  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by quick-docker-setup.sh for local development only.
TZ=Asia/Ho_Chi_Minh
JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Ho_Chi_Minh

MYSQL_ROOT_PASSWORD=$mysql_root_password
DB_HOST=mysql
DB_PORT=3306
DB_JDBC_URL=jdbc:mysql://mysql:3306/finsight?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
DB_USER=finsight
DB_PASSWORD=$db_password
DB_NAME=finsight

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=$redis_password
REDIS_DATABASE=0
REDIS_CACHE_TTL=3600

KAFKA_URLS=kafka:19092
KAFKA_TOPIC_MARKET_DATA=market-data
KAFKA_TOPIC_WEBHOOKS=market-payment
KAFKA_TOPIC_REST=market-rest
KAFKA_TOPIC_INGESTION=market-ingestion
KAFKA_TOPIC_INGESTION_REPLY=
KAFKA_REQUEST_TIMEOUT_MS=15000

MQTT_URL=tcp://mosquitto:1883
MQTT_USERNAME=
MQTT_PASSWORD=
MQTT_TOPIC_MARKET_DATA=market-data

# The optional live-market profile needs real authorized DNSE values.
DATAFEED_TOKENURL=wss://datafeed-lts-krx.dnse.com.vn:443/wss
DATAFEED_INVERSTORURL=unused-unless-live-market-profile-is-enabled
DATAFEED_WEBSOCKETURL=unused-unless-live-market-profile-is-enabled
DATAFEED_USERNAME=
DATAFEED_PASSWORD=

# Placeholders keep the core demo bootable. Payments require real PayOS credentials.
PAYOS_CLIENT_ID=unused-unless-payments-are-enabled
PAYOS_API_KEY=unused-unless-payments-are-enabled
PAYOS_CHECKSUM_KEY=unused-unless-payments-are-enabled

MAIL_HOST=smtp.example.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=

VITE_API_BASE_URL=http://localhost:8080
VITE_INGESTION_API_BASE_URL=http://localhost:8080/ingestion
VITE_MQTT_BROKER_URL=ws://localhost:9001/mqtt
VITE_MQTT_TOPIC=market-data
APP_DOMAIN=localhost:8080
EOF

  echo "Created $ENV_FILE with generated local passwords."
}

wait_for_kafka() {
  local attempt
  echo "Waiting for Kafka..."
  for attempt in {1..60}; do
    if compose exec -T kafka /opt/kafka/bin/kafka-topics.sh \
      --list --bootstrap-server kafka:19092 >/dev/null 2>&1; then
      return
    fi
    sleep 2
  done
  fail "Kafka did not become ready. Run ./quick-docker-setup.sh logs for details."
}

create_kafka_topics() {
  local topic
  for topic in market-data market-payment market-rest market-ingestion; do
    compose exec -T kafka /opt/kafka/bin/kafka-topics.sh \
      --create \
      --if-not-exists \
      --topic "$topic" \
      --partitions 3 \
      --replication-factor 1 \
      --bootstrap-server kafka:19092 >/dev/null
  done
  echo "Kafka topics are ready."
}

wait_for_gateway() {
  local attempt
  echo "Waiting for the REST health check..."
  for attempt in {1..90}; do
    if compose exec -T gateway wget -qO- http://localhost/health >/dev/null 2>&1; then
      echo "FinSight is ready."
      return
    fi
    sleep 2
  done
  fail "The health check did not pass. Run ./quick-docker-setup.sh logs for details."
}

start_stack() {
  create_local_env
  compose config --quiet

  echo "Starting MySQL, Redis, Kafka, and MQTT..."
  compose up -d --wait --wait-timeout 180 mysql redis kafka mosquitto
  wait_for_kafka
  create_kafka_topics

  echo "Building FinSight images. The first build can take several minutes..."
  compose build --pull \
    market-rest-1 \
    market-rest-2 \
    market-ingestion \
    market-realtime \
    market-frontend

  echo "Starting the core FinSight application..."
  compose up -d \
    market-realtime \
    market-rest-1 \
    market-rest-2 \
    market-ingestion \
    market-frontend \
    gateway

  wait_for_gateway
  compose ps
  echo
  echo "FinSight: http://localhost:8080"
  echo "Health:   http://localhost:8080/health"
  echo "Swagger:  http://localhost:8080/api-docs/"
  echo
  echo "A new MySQL volume is initialized from the bundled thesis database snapshot."
  echo "Payment and live-market integrations are disabled until configured."
}

case "$ACTION" in
  setup)
    require_docker
    start_stack
    ;;
  status)
    require_docker
    [[ -f "$ENV_FILE" ]] || fail "Missing $ENV_FILE. Run ./quick-docker-setup.sh first."
    compose ps
    ;;
  logs)
    require_docker
    [[ -f "$ENV_FILE" ]] || fail "Missing $ENV_FILE. Run ./quick-docker-setup.sh first."
    compose logs --tail=200 -f
    ;;
  stop)
    require_docker
    [[ -f "$ENV_FILE" ]] || fail "Missing $ENV_FILE. Run ./quick-docker-setup.sh first."
    compose down
    ;;
  -h|--help|help)
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
